name: 'Twitter Release Action'
description: 'Notifies Twitter of a version Release'
author: 'RLittlesII'
inputs:
  token:
    description: 'Twitter token'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
